name: btn
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pytorch
  - pytorch-cuda
  - numpy
  - scipy
  - scikit-learn
  - numba
  - tqdm
  - pip
  - pip:
      - ucimlrepo==0.0.7
      - quimb==1.11.2
      - cotengra==0.7.5
      - autoray==0.8.0
